/*
  sw.js — Siralim Ultimate Build Calculator service worker.

  WHY: content-hash `?v=` busting fixes every SUB-resource, but it cannot bust
  index.html itself — the entry document is fetched by its plain URL, GitHub Pages
  serves it `Cache-Control: max-age=600` (no header override on Pages), and browsers
  add heuristic/bfcache freshness on top. A stale index.html points at the OLD `?v=`
  hashes, defeating the whole chain at the root ("hard-refresh to see my update").
  This SW closes the gap: navigations are network-first, so an online user always
  revalidates the HTML shell (fresh pointers).

  CACHES (two, on purpose):
    - SHELL  (versioned by BUILD) — the HTML shell + hashed js/css + icons/manifest.
             Purged on every deploy so nothing stale lingers.
    - ASSETS (stable name)        — the ~6k sprite PNGs. NOT tied to BUILD, so a code
             deploy does NOT re-download 19 MB of art; the set is keyed internally
             by the precache-list version instead.

  STRATEGY:
    - navigation / HTML   -> network-first (SHELL)  — fresh online, cached offline
    - /assets/* requests  -> cache-first  (ASSETS)  — sprites; also background-precached
    - other same-origin   -> cache-first  (SHELL)   — hashed js/css (immutable per ?v=)

  OFFLINE COMPLETENESS: on a page signal we background-precache every sprite from
  precache-list.json (generated by build-data.mjs) so airplane-mode works fully,
  not just for art you happened to view online. Runs once per list version.

  BUILD below is stamped by build-data.mjs each build.
*/
const BUILD = "34883645";
const SHELL = `su-shell-${BUILD}`;
const ASSETS = "su-assets"; // stable across deploys; versioned internally by the list
const KEEP = new Set([SHELL, ASSETS]);
const LIST_MARKER = "__list_version__";

self.addEventListener("install", () => {
  self.skipWaiting();
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(names.filter((n) => !KEEP.has(n)).map((n) => caches.delete(n)));
      await self.clients.claim();
    })()
  );
});

function isNavigation(req) {
  return (
    req.mode === "navigate" ||
    (req.method === "GET" && (req.headers.get("accept") || "").includes("text/html"))
  );
}
const isAsset = (url) => url.pathname.includes("/assets/");

async function cacheFirst(request, cacheName) {
  const cache = await caches.open(cacheName);
  const hit = await cache.match(request);
  if (hit) return hit;
  const fresh = await fetch(request);
  if (fresh.ok) cache.put(request, fresh.clone());
  return fresh;
}

self.addEventListener("fetch", (e) => {
  const { request } = e;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return; // let CDN/analytics pass straight through

  if (isNavigation(request)) {
    e.respondWith(
      (async () => {
        try {
          // cache:"reload" bypasses the HTTP cache so we get index.html straight from the network —
          // GitHub Pages serves it max-age=600, and a plain fetch() would revalidate against that stale
          // copy (old ?v= tokens) for up to 10 min, defeating the point of network-first navigations.
          const fresh = await fetch(request, { cache: "reload" });
          (await caches.open(SHELL)).put(request, fresh.clone());
          return fresh;
        } catch {
          const shell = await caches.open(SHELL);
          return (
            (await shell.match(request)) ||
            (await shell.match("./index.html")) ||
            Response.error()
          );
        }
      })()
    );
    return;
  }

  e.respondWith(cacheFirst(request, isAsset(url) ? ASSETS : SHELL));
});

// Background-precache the full sprite set on a page signal. Idempotent: exits early
// once the current list version is fully cached, so it's cheap on every load.
async function precacheAssets() {
  let list;
  try {
    const r = await fetch("precache-list.json", { cache: "no-cache" });
    if (!r.ok) return;
    list = await r.json();
  } catch {
    return;
  }
  const cache = await caches.open(ASSETS);
  const marker = await cache.match(LIST_MARKER);
  if (marker && (await marker.text()) === list.v) return; // already precached for this version

  const urls = list.urls || [];
  const CHUNK = 80;
  for (let i = 0; i < urls.length; i += CHUNK) {
    await Promise.all(
      urls.slice(i, i + CHUNK).map(async (u) => {
        try {
          if (!(await cache.match(u))) {
            const res = await fetch(u);
            if (res.ok) await cache.put(u, res);
          }
        } catch {
          /* tolerate individual asset failures */
        }
      })
    );
  }
  await cache.put(LIST_MARKER, new Response(list.v));
}

self.addEventListener("message", (e) => {
  if (e.data && e.data.type === "precache") e.waitUntil(precacheAssets());
});
